package project2;

import java.awt.GridLayout;
import java.awt.List;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.*;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;

public class AuthorityEntry extends javax.swing.JFrame {

     JFrame jFrame=new JFrame("Sign Up Form");
    
    JTextField jTextFiledSubjectName=new JTextField();
    
    JTextField jTextFiledSubjectTitle=new JTextField();
    
    JTextField jTextFiledSubjectSection=new JTextField();
    
    JTextField jTextFiledSubjectFaculty=new JTextField();
    
    JTextField jTextFiledSubjectStudent=new JTextField();
   
    JLabel jLabelSubjectName=new JLabel("Product Name");
    
    JLabel jLabelSubjectTitle=new JLabel("Product code");
    
    JLabel jLabelSubjectSection=new JLabel("Price");
    
    JLabel jLabelSubjectFaculty=new JLabel("Stores");
    
    JLabel jLabelSubjectStudent=new JLabel("Quantity");
    
    JLabel jLabel=new JLabel();

JList<ProductInformationAll> jList=new JList<ProductInformationAll>();
    
    DefaultListModel<ProductInformationAll> defaultListModel=new DefaultListModel<>();
    
   //static JLabel jLabel=new JLabel();
    
    JPanel jPanel=new JPanel();
    
    JSplitPane jSplitPane=new JSplitPane();
    
JScrollBar jScrollBar=new JScrollBar();
    
    JButton jButtonUpdate=new JButton("Update Data");
    
    JButton jButtonDelete=new JButton("Delete Data");
    
    FileWriter fileWriter;
    ProductInformationAll courseInformationSampleClassAll=new ProductInformationAll();
    /**
     * Creates new form AuthorityEntry
     */
    public AuthorityEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCourseName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFiledCourseTitle = new javax.swing.JTextPane();
        jLabelCourseSection = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFiledCourseName = new javax.swing.JTextPane();
        jLabelCourseTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFiledCourseStudent = new javax.swing.JTextPane();
        jLabelCourseFaculty = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFiledCourseSection = new javax.swing.JTextPane();
        jLabelCourseStudent = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextFiledCourseFaculty = new javax.swing.JTextPane();
        jButtonEnter = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        jButtonShowData = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 96, 96));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Authority Entry Product Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("     -");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(96, 96, 96));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCourseName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseName.setText("Product Name:");

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTextFiledCourseTitle);

        jLabelCourseSection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseSection.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseSection.setText("Price:");

        jScrollPane2.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane2.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextFiledCourseName);

        jLabelCourseTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseTitle.setText("Product Code:");

        jScrollPane3.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane3.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jTextFiledCourseStudent);

        jLabelCourseFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseFaculty.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseFaculty.setText("Stores:");

        jScrollPane4.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane4.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jTextFiledCourseSection);

        jLabelCourseStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCourseStudent.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseStudent.setText("Quantity:");

        jScrollPane5.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane5.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(jTextFiledCourseFaculty);

        jButtonEnter.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEnter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(154, 0, 76));
        jButtonEnter.setText("Add");
        jButtonEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnterMouseClicked(evt);
            }
        });

        ClearAll.setBackground(new java.awt.Color(0, 204, 204));
        ClearAll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearAll.setForeground(new java.awt.Color(154, 0, 76));
        ClearAll.setText("Clear All");
        ClearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearAllMouseClicked(evt);
            }
        });
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });

        jButtonShowData.setBackground(new java.awt.Color(0, 204, 204));
        jButtonShowData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonShowData.setForeground(new java.awt.Color(154, 0, 76));
        jButtonShowData.setText("Show Data");
        jButtonShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShowDataMouseClicked(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(154, 0, 76));
        jButtonSearch.setText("Search");
        jButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCourseName)
                            .addComponent(jLabelCourseTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCourseFaculty)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabelCourseStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCourseSection)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(55, 55, 55))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonShowData)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButtonEnter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourseName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCourseTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourseSection)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourseFaculty)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourseStudent)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonEnter)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowData)
                .addGap(11, 11, 11)
                .addComponent(jButtonSearch)
                .addGap(18, 18, 18)
                .addComponent(ClearAll)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void ClearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearAllMouseClicked
        // TODO add your handling code here:
        
        jTextFiledCourseName.setText("");
        jTextFiledCourseTitle.setText("");
        jTextFiledCourseSection.setText("");
        jTextFiledCourseFaculty.setText("");
        jTextFiledCourseStudent.setText("");
        
    }//GEN-LAST:event_ClearAllMouseClicked

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
        // TODO add your handling code here:

        jTextFiledCourseName.setText("");
        jTextFiledCourseTitle.setText("");
        jTextFiledCourseSection.setText("");
        jTextFiledCourseFaculty.setText("");
        jTextFiledCourseStudent.setText("");
        
    }//GEN-LAST:event_ClearAllActionPerformed

    private void jButtonEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnterMouseClicked
        // TODO add your handling code here:
    File file=new File("C:/Project File/MaterialData.txt");    
        
    try{
        
        fileWriter=new FileWriter(file,true);
            BufferedWriter bf=new BufferedWriter(fileWriter);
            PrintWriter printWriter=new PrintWriter(bf);
        
            printWriter.print(jLabelCourseName.getText().toString().trim()+" : "+jTextFiledCourseName.getText().toString()+"\n");
            printWriter.print(jLabelCourseTitle.getText().toString().trim()+" : "+jTextFiledCourseTitle.getText().toString().trim()+"\n");
            printWriter.print(jLabelCourseSection.getText().toString().trim()+" : "+jTextFiledCourseSection.getText().toString().trim()+"\n");
            printWriter.print(jLabelCourseFaculty.getText().toString().trim()+" : "+jTextFiledCourseFaculty.getText().toString().trim()+"\n");
            printWriter.print(jLabelCourseStudent.getText().toString().trim()+" : "+jTextFiledCourseStudent.getText().toString().trim()+"\n"+"\n"+"\n");
            
             printWriter.close();
    
             JOptionPane.showMessageDialog(null, "The data is stored succesully");
             
    }catch(Exception exception){
        
        JOptionPane.showMessageDialog(null, exception);
        
    }    
    
    }//GEN-LAST:event_jButtonEnterMouseClicked

    private void jButtonShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShowDataMouseClicked
        // TODO add your handling code here:
        
         File file=new File("C:/Project File/MaterialData.txt");
    
    jList.setModel(defaultListModel);
        try{
            int rownumber=0;
            Scanner scanner1=new Scanner(file);
            Scanner scanner=new Scanner(file);
            
    LinkedList <ProductInformationAll> arrayList=new LinkedList<ProductInformationAll>();
              
    while(scanner.hasNext()){
        
   String courseName=scanner.nextLine();
        
   String courseTitle=scanner.nextLine();
   
   String courseSection=scanner.nextLine();
        
   String courseFaculty=scanner.nextLine();
   
   String courseStudent=scanner.nextLine();
   
   String line1=scanner.nextLine();
   
   String line2=scanner.nextLine();
   
   defaultListModel.addElement(new ProductInformationAll( courseName,  courseTitle,  courseFaculty,  courseSection,  courseStudent));
   
    }
    
    jSplitPane.setLeftComponent(new JScrollPane(jList));
       
       jPanel.add(jLabel);
       
       jSplitPane.setRightComponent(jPanel);
       
   GridLayout gridLayout=new GridLayout();
    
    gridLayout.setColumns(1);
gridLayout.setRows(3);
        
jFrame.setLayout(gridLayout);

//jFrame.add(jList);
    jFrame.pack();
    jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
jFrame.setSize(900, 600);
jFrame.add(jSplitPane);
jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
jFrame.show();

//jFrame.add(jButtonUpdate);
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }         
    }//GEN-LAST:event_jButtonShowDataMouseClicked

    private void jButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchMouseClicked
        // TODO add your handling code here:
        
        ProductUpdateDelete registerForm=new ProductUpdateDelete();
        
        registerForm.setVisible(true);
        
        registerForm.pack();
        
        registerForm.setLocationRelativeTo(null);
        
        registerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.dispose();  
        
        
    }//GEN-LAST:event_jButtonSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorityEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorityEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorityEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorityEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorityEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCourseFaculty;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseSection;
    private javax.swing.JLabel jLabelCourseStudent;
    private javax.swing.JLabel jLabelCourseTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextFiledCourseFaculty;
    private javax.swing.JTextPane jTextFiledCourseName;
    private javax.swing.JTextPane jTextFiledCourseSection;
    private javax.swing.JTextPane jTextFiledCourseStudent;
    private javax.swing.JTextPane jTextFiledCourseTitle;
    // End of variables declaration//GEN-END:variables
}
