package project2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;//

public class SignUpAndSignInForm extends javax.swing.JFrame {

    FileWriter fileWriter;
    
    File file=new File("C:/Project File/CustomerInfo.txt");
    
    /**
     * Creates new form SignUpAndSignInForm
     */
    public SignUpAndSignInForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        ClearAll = new javax.swing.JButton();
        jButtonSignUp = new javax.swing.JButton();
        jButtonSignIn = new javax.swing.JButton();
        jTextFiledEmail = new javax.swing.JTextField();
        jTextFiledUserName = new javax.swing.JTextField();
        jTextFiledPassword = new javax.swing.JPasswordField();
        jButtonAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 96, 96));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Super Shop Management");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("     -");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(96, 96, 96));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPassword.setText("Password:");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName.setText("UserName:");

        ClearAll.setBackground(new java.awt.Color(0, 204, 204));
        ClearAll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearAll.setForeground(new java.awt.Color(255, 128, 0));
        ClearAll.setText("Clear All");
        ClearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearAllMouseClicked(evt);
            }
        });

        jButtonSignUp.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(255, 128, 0));
        jButtonSignUp.setText("Register");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });

        jButtonSignIn.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSignIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSignIn.setForeground(new java.awt.Color(255, 128, 0));
        jButtonSignIn.setText("Sign In");
        jButtonSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSignInMouseClicked(evt);
            }
        });
        jButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInActionPerformed(evt);
            }
        });

        jTextFiledEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFiledUserName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFiledUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiledUserNameActionPerformed(evt);
            }
        });

        jButtonAdmin.setBackground(new java.awt.Color(0, 204, 204));
        jButtonAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAdmin.setForeground(new java.awt.Color(255, 128, 0));
        jButtonAdmin.setText("Authority");
        jButtonAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdminMouseClicked(evt);
            }
        });
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFiledEmail)
                    .addComponent(jTextFiledPassword)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFiledUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jTextFiledUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFiledPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFiledEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonSignIn)
                .addGap(25, 25, 25)
                .addComponent(jButtonAdmin)
                .addGap(18, 18, 18)
                .addComponent(jButtonSignUp)
                .addGap(18, 18, 18)
                .addComponent(ClearAll)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
         System.exit(0);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        this.setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // TODO add your handling code here:
        
        try{
    
    File file=new File("C:/Project File/CustomerInfo.txt");
    
    fileWriter=new FileWriter(file,true);
     BufferedWriter bf=new BufferedWriter(fileWriter);
    PrintWriter printWriter=new PrintWriter(bf);
    
    printWriter.print(jLabelUserName.getText().toString()+" :  "+jTextFiledUserName.getText().toString()+"\n");
    printWriter.print(jLabelPassword.getText().toString()+" : "+jTextFiledPassword.getText().toString()+"\n");
    printWriter.print(jLabelEmail.getText().toString()+" : "+jTextFiledEmail.getText().toString()+"\n"+"\n"+"\n");
    
   printWriter.close();
    
    JOptionPane.showMessageDialog(null, "It is stored succesfully");
    
}catch(Exception exception){
    
    JOptionPane.showMessageDialog(null, exception);
    
}    
        
       // JOptionPane.showMessageDialog(null, "It us stored succesfully");
        //registerbutton
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void ClearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearAllMouseClicked
        // TODO add your handling code here:
    jTextFiledUserName.setText("");
    jTextFiledPassword.setText("");
    jTextFiledEmail.setText("");
        
    }//GEN-LAST:event_ClearAllMouseClicked

    private void jButtonAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdminMouseClicked
        // TODO add your handling code here:
        
    AuthoritySurityForm registerForm=new AuthoritySurityForm();
        
        registerForm.setVisible(true);
        
        registerForm.pack();
        
        registerForm.setLocationRelativeTo(null);
        
        registerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.dispose();    
        
    }//GEN-LAST:event_jButtonAdminMouseClicked

    private void jButtonSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignInMouseClicked
        // TODO add your handling code here:
        
         File file=new File("C:/Project File/CustomerInfo.txt");
        
        try {
            
            Scanner scanner=new Scanner(file);
            int checker=0;
            String name=jLabelUserName.getText().toString().trim()+" :  "+jTextFiledUserName.getText().toString().trim();
            String password=jLabelPassword.getText().toString().trim()+" : "+jTextFiledPassword.getText().toString().trim();
            String email=jLabelEmail.getText().toString().trim()+" : "+jTextFiledEmail.getText().toString().trim();
          
            while(scanner.hasNext()){
                
                String name1=scanner.nextLine();
              //  JOptionPane.showMessageDialog(null, name1);
                String password1=scanner.nextLine();
                //JOptionPane.showMessageDialog(null, password1);
                String email1=scanner.nextLine();
                //JOptionPane.showMessageDialog(null, email1);
                String line1=scanner.nextLine();
                String line2=scanner.nextLine();
                
                if(name1.equals(name) && password1.equals(password) && email1.equals(email)){
                    
                    JOptionPane.showMessageDialog(null, "Logged In Sucessfully");
                    
                    checker=1;
                    
                    break;
                
                }
                
            }
            
            if(checker==1){
               String product=jLabelUserName.getText().toString()+" :  "+jTextFiledUserName.getText().toString().trim();
            String productemailpassword=jLabelPassword.getText().toString()+" : "+jTextFiledPassword.getText().toString().trim();
            String productemail=jLabelEmail.getText().toString()+" : "+jTextFiledEmail.getText().toString().trim();
                ProductTaken productTaken=new ProductTaken(product,productemailpassword,productemail);
               
     productTaken.createJrameFrom();
            
            }
            
           else if(checker==0){
                JOptionPane.showMessageDialog(null, "Logged In is not Sucessfully");
            }
            
        } catch (FileNotFoundException ex) {
           // Logger.getLogger(SignUpAndSignInForm.class.getName()).log(Level.SEVERE, null, ex);
        
           JOptionPane.showMessageDialog(null, ex);
        
        }
         
    }//GEN-LAST:event_jButtonSignInMouseClicked

    private void jButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignInActionPerformed

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jTextFiledUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiledUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFiledUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpAndSignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpAndSignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpAndSignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpAndSignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpAndSignInForm().setVisible(true);
            }
        });
    }
//Sadman Tajwer
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonSignIn;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFiledEmail;
    private javax.swing.JPasswordField jTextFiledPassword;
    private javax.swing.JTextField jTextFiledUserName;
    // End of variables declaration//GEN-END:variables
}
